/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI specification */
        get: operations["openapi_spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyticsFilter: {
            kind?: string | null;
            model?: string | null;
            provider?: string | null;
            /** Format: date-time */
            since?: string | null;
            status?: string | null;
            trace_id?: string | null;
            /** Format: date-time */
            until?: string | null;
        };
        AnalyticsGroup: {
            key: {
                [key: string]: string;
            };
            metrics: components["schemas"]["MetricValues"];
        };
        /** @enum {string} */
        AnalyticsMetric: "total_cost" | "total_input_tokens" | "total_output_tokens" | "total_tokens" | "avg_latency_ms" | "span_count" | "error_count";
        AnalyticsQuery: {
            filter?: components["schemas"]["AnalyticsFilter"];
            group_by?: components["schemas"]["GroupByField"][];
            metrics: components["schemas"]["AnalyticsMetric"][];
        };
        AnalyticsResponse: {
            groups: components["schemas"]["AnalyticsGroup"][];
            totals: components["schemas"]["MetricValues"];
        };
        AnalyticsSummary: {
            /** Format: double */
            avg_latency_ms: number;
            cost_by_model: components["schemas"]["ModelCost"][];
            error_count: number;
            models_used: string[];
            providers_used: string[];
            tokens_by_model: components["schemas"]["ModelTokens"][];
            /** Format: double */
            total_cost: number;
            total_llm_calls: number;
            total_spans: number;
            /** Format: int64 */
            total_tokens: number;
            total_traces: number;
        };
        ClaimRequest: {
            claimed_by: string;
        };
        ClearedAll: {
            message: string;
        };
        CompleteSpanRequest: {
            output?: unknown;
        };
        CreateDatapointRequest: {
            kind: components["schemas"]["DatapointKind"];
        };
        CreateDatasetRequest: {
            description?: string | null;
            name: string;
        };
        CreateSpanRequest: {
            input?: unknown;
            kind: components["schemas"]["SpanKind"];
            name: string;
            parent_id?: string | null;
            trace_id: string;
        };
        CreateTraceRequest: {
            name?: string | null;
            tags?: string[];
        };
        CreatedSpan: {
            id: string;
            trace_id: string;
        };
        Datapoint: {
            /** Format: date-time */
            created_at: string;
            dataset_id: string;
            id: string;
            kind: components["schemas"]["DatapointKind"];
            source: components["schemas"]["DatapointSource"];
            source_span_id?: string | null;
        };
        DatapointKind: {
            expected?: null | components["schemas"]["Message"];
            messages: components["schemas"]["Message"][];
            metadata?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            type: "llm_conversation";
        } | {
            actual_output?: unknown;
            expected_output?: unknown;
            input: unknown;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: double */
            score?: number | null;
            /** @enum {string} */
            type: "generic";
        };
        DatapointListResponse: {
            count: number;
            datapoints: components["schemas"]["Datapoint"][];
        };
        /** @enum {string} */
        DatapointSource: "manual" | "span_export" | "file_upload";
        Dataset: {
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            id: string;
            name: string;
            org_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        DatasetListResponse: {
            count: number;
            datasets: components["schemas"]["DatasetResponse"][];
        };
        DatasetResponse: components["schemas"]["Dataset"] & {
            datapoint_count: number;
        };
        DeletedTrace: {
            spans_deleted: number;
            trace_id: string;
        };
        EnqueueRequest: {
            datapoint_ids: string[];
        };
        EnqueueResponse: {
            enqueued: number;
        };
        ExportData: {
            traces: {
                [key: string]: components["schemas"]["Span"][];
            };
        };
        ExportParams: {
            trace_id?: string | null;
        };
        ExportSpanRequest: {
            span_id: string;
        };
        FailSpanRequest: {
            error: string;
        };
        FileListResponse: {
            count: number;
            files: components["schemas"]["FileVersion"][];
        };
        FileQueryParams: {
            path_prefix?: string | null;
            /** Format: date-time */
            since?: string | null;
            /** Format: date-time */
            until?: string | null;
        };
        FileVersion: {
            /** Format: date-time */
            created_at: string;
            created_by_span?: string | null;
            hash: string;
            path: string;
            /** Format: int64 */
            size: number;
        };
        FileVersionsResponse: {
            count: number;
            path: string;
            versions: components["schemas"]["FileVersion"][];
        };
        /** @enum {string} */
        GroupByField: "model" | "provider" | "kind" | "status" | "trace" | "day" | "hour";
        HealthResponse: {
            instance?: string | null;
            region?: string | null;
            status: string;
            storage: components["schemas"]["StorageHealth"];
            /** Format: int64 */
            uptime_secs: number;
            version: string;
        };
        ImportResponse: {
            dataset_id: string;
            imported: number;
        };
        Message: {
            content: string;
            role: string;
        };
        MetricValues: {
            /** Format: double */
            avg_latency_ms?: number | null;
            /** Format: int64 */
            error_count?: number | null;
            /** Format: int64 */
            span_count?: number | null;
            /** Format: double */
            total_cost?: number | null;
            /** Format: int64 */
            total_input_tokens?: number | null;
            /** Format: int64 */
            total_output_tokens?: number | null;
            /** Format: int64 */
            total_tokens?: number | null;
        };
        ModelCost: {
            /** Format: double */
            cost: number;
            model: string;
            span_count: number;
        };
        ModelTokens: {
            /** Format: int64 */
            input_tokens: number;
            model: string;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            total_tokens: number;
        };
        QueueCounts: {
            claimed: number;
            completed: number;
            pending: number;
        };
        QueueItem: {
            /** Format: date-time */
            claimed_at?: string | null;
            claimed_by?: string | null;
            /** Format: date-time */
            created_at: string;
            datapoint_id: string;
            dataset_id: string;
            edited_data?: unknown;
            id: string;
            original_data?: unknown;
            status: components["schemas"]["QueueItemStatus"];
        };
        /** @enum {string} */
        QueueItemStatus: "pending" | "claimed" | "completed";
        QueueListResponse: {
            counts: components["schemas"]["QueueCounts"];
            items: components["schemas"]["QueueItem"][];
        };
        Span: {
            /** Format: date-time */
            ended_at?: string | null;
            id: string;
            input?: unknown;
            kind: components["schemas"]["SpanKind"];
            name: string;
            org_id?: string | null;
            output?: unknown;
            parent_id?: string | null;
            /** Format: date-time */
            started_at: string;
            status: components["schemas"]["SpanStatus"];
            trace_id: string;
        };
        SpanKind: {
            /** Format: int64 */
            bytes_read: number;
            file_version?: string | null;
            path: string;
            /** @enum {string} */
            type: "fs_read";
        } | {
            /** Format: int64 */
            bytes_written: number;
            file_version: string;
            path: string;
            /** @enum {string} */
            type: "fs_write";
        } | {
            /** Format: double */
            cost?: number | null;
            input_preview?: string | null;
            /** Format: int64 */
            input_tokens?: number | null;
            model: string;
            output_preview?: string | null;
            /** Format: int64 */
            output_tokens?: number | null;
            provider?: string | null;
            /** @enum {string} */
            type: "llm_call";
        } | {
            attributes?: {
                [key: string]: unknown;
            };
            kind: string;
            /** @enum {string} */
            type: "custom";
        };
        SpanList: {
            count: number;
            spans: components["schemas"]["Span"][];
        };
        SpanQueryParams: {
            kind?: string | null;
            model?: string | null;
            name_contains?: string | null;
            path?: string | null;
            provider?: string | null;
            /** Format: date-time */
            since?: string | null;
            status?: string | null;
            trace_id?: string | null;
            /** Format: date-time */
            until?: string | null;
        };
        SpanStatus: "running" | "completed" | {
            failed: {
                error: string;
            };
        };
        Stats: {
            span_count: number;
            trace_count: number;
        };
        StorageHealth: {
            backend: string;
            span_count: number;
            trace_count: number;
        };
        SubmitRequest: {
            edited_data?: unknown;
        };
        Trace: {
            /** Format: date-time */
            ended_at?: string | null;
            id: string;
            machine_id?: string | null;
            name?: string | null;
            org_id?: string | null;
            /** Format: date-time */
            started_at: string;
            tags?: string[];
        };
        TraceListResponse: {
            count: number;
            traces: components["schemas"]["Trace"][];
        };
        TrackedFile: {
            /** Format: date-time */
            created_at: string;
            current_hash: string;
            path: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateDatasetRequest: {
            description?: string | null;
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    openapi_spec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI JSON specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
// regenerated
